# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PwHrkPIiguK_CzovtnL42-zPs_PaSUzY
"""

!pip install PyPDF2
!pip install langchain
!pip install langchain-text-splitters
!pip install langchain-community
!pip install sentence-transformers
!pip install chromadb

print("✅ All packages installed!")

from google.colab import files

print("📂 Click 'Choose Files' and select your IBM ITX PDF...")
uploaded = files.upload()


import os
pdf_filename = list(uploaded.keys())[0]
print(f"✅ Uploaded: {pdf_filename}")

import PyPDF2
import json

def extract_itx_pdf(pdf_path):
    chunks = []

    with open(pdf_path, 'rb') as f:
        reader = PyPDF2.PdfReader(f)
        total_pages = len(reader.pages)
        print(f"📄 Total pages found: {total_pages}")

        for page_num in range(total_pages):
            page = reader.pages[page_num]
            text = page.extract_text()

            if text and len(text.strip()) > 100:
                chunks.append({
                    "page": page_num + 1,
                    "content": text.strip(),
                    "source": f"IBM_ITX_Page_{page_num+1}"
                })


            if (page_num + 1) % 100 == 0:
                print(f"  ⏳ Processed {page_num+1}/{total_pages} pages...")

    print(f"✅ Extracted {len(chunks)} pages with content")
    return chunks


raw_chunks = extract_itx_pdf(pdf_filename)

from langchain_text_splitters import RecursiveCharacterTextSplitter

def smart_chunk(chunks, chunk_size=512, overlap=50):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=overlap,
        separators=["\n\n", "\n", ".", " "]
    )

    all_chunks = []
    for chunk in chunks:
        splits = splitter.split_text(chunk["content"])
        for i, split in enumerate(splits):
            all_chunks.append({
                "content": split,
                "source": chunk["source"],
                "chunk_id": f"{chunk['source']}_chunk_{i}"
            })

    return all_chunks

processed_chunks = smart_chunk(raw_chunks)
print(f" Total chunks created: {len(processed_chunks)}")

with open("itx_chunks.json", "w") as f:
    json.dump(processed_chunks, f, indent=2)

print(" Saved to itx_chunks.json")

from sentence_transformers import SentenceTransformer
import chromadb

print(" Loading embedding model (downloads ~90MB first time)...")
embedder = SentenceTransformer('all-MiniLM-L6-v2')
print(" Embedding model loaded!")

client = chromadb.PersistentClient(path="./itx_vectordb")

try:
    client.delete_collection("ibm_itx_docs")
    print(" Cleared old collection")
except:
    pass

collection = client.get_or_create_collection(
    name="ibm_itx_docs",
    metadata={"hnsw:space": "cosine"}
)
print(f" Vector DB ready! Will store {len(processed_chunks)} chunks")

def build_vector_db(chunks, batch_size=100):
    total_batches = (len(chunks) // batch_size) + 1

    for i in range(0, len(chunks), batch_size):
        batch       = chunks[i:i+batch_size]
        texts       = [c["content"]  for c in batch]
        ids         = [c["chunk_id"] for c in batch]
        metadatas   = [{"source": c["source"]} for c in batch]

        embeddings  = embedder.encode(texts, show_progress_bar=False)

        collection.add(
            embeddings=embeddings.tolist(),
            documents=texts,
            ids=ids,
            metadatas=metadatas
        )

        batch_num = i // batch_size + 1
        done      = min(i + batch_size, len(chunks))
        print(f" Batch {batch_num}/{total_batches} | Chunks stored: {done}/{len(chunks)}")

build_vector_db(processed_chunks)
print("\n Vector DB built and saved successfully!")

def retrieve_context(query, top_k=3):
    query_embedding = embedder.encode([query])
    results = collection.query(
        query_embeddings=query_embedding.tolist(),
        n_results=top_k
    )
    return results["documents"][0]

test_query = "How to map EDI 850 purchase order in ITX?"
results = retrieve_context(test_query)

print(f"🔍 Query: {test_query}\n")
print("=" * 60)
for i, r in enumerate(results):
    print(f"\n📄 Result {i+1}:")
    print(r[:400])
    print("-" * 40)

import PyPDF2
import json
import hashlib
import uuid
from datetime import datetime

CHUNK_CATEGORIES = {
    "type_tree":     ["type tree", "typetree", "root type", "group", "item", "component", "cardinality"],
    "mapping_rules": ["map", "mapping", "transform", "source", "target", "rule", "mtt", "mms"],
    "functions":     ["function", "substr", "concat", "lookup", "arithmetic", "date format"],
    "cards":         ["card", "initiator", "terminator", "release", "delimiter"],
    "validation":    ["valid", "mandatory", "optional", "min", "max", "length", "pattern"],
    "launcher":      ["launch", "execute", "run", "command", "batch"],
    "trace_logs":    ["trace", "log", "audit", "debug", "error"],
    "syntax":        ["syntax", "rule", "grammar", "format", "definition"],
    "examples":      ["example", "sample", "demo", "use case", "scenario"],
    "error_docs":    ["error", "exception", "fault", "warning", "fail"],
    "configuration": ["config", "setting", "parameter", "property", "install"],
    "general":       []  # fallback
}

def detect_category(text):
    """Detect EDIAI chunk category from text content"""
    text_lower = text.lower()
    for category, keywords in CHUNK_CATEGORIES.items():
        if any(kw in text_lower for kw in keywords):
            return category
    return "general"

def sha256_hash(text):
    return hashlib.sha256(text.encode()).hexdigest()

def extract_itx_pdf(pdf_path):
    """Extract pages with EDIAI Document model structure"""
    chunks = []

    with open(pdf_path, 'rb') as f:
        reader = PyPDF2.PdfReader(f)
        total_pages = len(reader.pages)
        print(f"📄 Total pages: {total_pages}")

        for page_num in range(total_pages):
            page    = reader.pages[page_num]
            text    = page.extract_text()

            if text and len(text.strip()) > 100:
                chunks.append({
                    "page":     page_num + 1,
                    "content":  text.strip(),
                    "source":   f"IBM_ITX_Page_{page_num+1}",
                    "category": detect_category(text)
                })

            if (page_num + 1) % 200 == 0:
                print(f"  ⏳ {page_num+1}/{total_pages} pages processed...")

    print(f" Extracted {len(chunks)} pages")
    return chunks

raw_chunks = extract_itx_pdf(pdf_filename)

from collections import Counter
cats = Counter(c["category"] for c in raw_chunks)
print("\n Category Distribution:")
for cat, count in cats.most_common():
    print(f"  {cat:<20} → {count} pages")

from langchain_text_splitters import RecursiveCharacterTextSplitter

def smart_chunk_ediai(raw_chunks, chunk_size=512, overlap=50):
    """
    Chunk pages and structure them as EDIAI Chunk model records
    matching: id, content, category, chunk_index, token_count,
              content_hash, source, prev_chunk_id, next_chunk_id
    """
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=overlap,
        separators=["\n\n", "\n", ".", " "]
    )

    all_chunks  = []
    global_idx  = 0

    for raw in raw_chunks:
        splits = splitter.split_text(raw["content"])

        for i, split in enumerate(splits):
            chunk_id = str(uuid.uuid4())
            all_chunks.append({

                "id":             chunk_id,
                "content":        split,
                "category":       raw["category"],
                "chunk_index":    global_idx,
                "token_count":    len(split.split()),
                "embedding_id":   f"emb_{chunk_id}",
                "content_hash":   sha256_hash(split),
                "parent_section": raw["source"],
                "chunk_id":       f"{raw['source']}_chunk_{i}",  # for ChromaDB
                "source":         raw["source"],
                "created_at":     datetime.utcnow().isoformat()
            })
            global_idx += 1

    # Link prev/next chunk IDs (doubly linked list)
    for i in range(len(all_chunks)):
        all_chunks[i]["prev_chunk_id"] = all_chunks[i-1]["id"] if i > 0 else None
        all_chunks[i]["next_chunk_id"] = all_chunks[i+1]["id"] if i < len(all_chunks)-1 else None

    return all_chunks

processed_chunks = smart_chunk_ediai(raw_chunks)
print(f" Total EDIAI chunks created: {len(processed_chunks)}")

# Save
with open("itx_chunks.json", "w") as f:
    json.dump(processed_chunks, f, indent=2)

print(" Saved → itx_chunks.json")

from sentence_transformers import SentenceTransformer
import chromadb

print(" Loading embedding model...")
embedder = SentenceTransformer('all-MiniLM-L6-v2')
print(" Embedding model loaded!")

chroma_client = chromadb.PersistentClient(path="./itx_vectordb")

try:
    chroma_client.delete_collection("ibm_itx_docs")
    print("  Cleared old collection")
except:
    pass

collection = chroma_client.get_or_create_collection(
    name="ibm_itx_docs",
    metadata={"hnsw:space": "cosine"}
)

print(f" Vector DB ready — {len(processed_chunks)} chunks to embed")

def build_vector_db(chunks, batch_size=100):
    total_batches = (len(chunks) // batch_size) + 1

    for i in range(0, len(chunks), batch_size):
        batch = chunks[i:i+batch_size]

        texts     = [c["content"]   for c in batch]
        ids       = [c["chunk_id"]  for c in batch]
        metadatas = [{
            "source":   c["source"],
            "category": c["category"],   # ← EDIAI category stored!
            "page":     c["parent_section"],
            "chunk_index": str(c["chunk_index"])
        } for c in batch]

        embeddings = embedder.encode(texts, show_progress_bar=False)

        collection.add(
            embeddings=embeddings.tolist(),
            documents=texts,
            ids=ids,
            metadatas=metadatas
        )

        done      = min(i + batch_size, len(chunks))
        batch_num = i // batch_size + 1
        print(f" Batch {batch_num}/{total_batches} | {done}/{len(chunks)} chunks stored")

build_vector_db(processed_chunks)
print("\n Vector DB built successfully!")

!pip install openai -q
print(" OpenAI SDK installed (used for DeepSeek)")

deepseek_client = OpenAI(
    api_key="ollama",
    base_url="http://localhost:11434/v1"
)

"""## Resources"""

model="deepseek-r1:8b"

pip install openai chromadb sentence-transformers fastapi uvicorn

